schema_version: 1

context:
  name: pypulseq
  version: "1.5.0.post1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pypulseq-${{ version }}.tar.gz
  sha256: 4b7f84906b7ca95fc602159b16af73973ca5e1e251b7e5070fa094ada3ec1059

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - coverage >=6.2
    - matplotlib-base >=3.5.2
    - numpy >=1.19.5
    - scipy >=1.8.1

tests:
  - python:
      imports: pypulseq
      pip_check: true
      python_version:
        - ${{ python_min }}.*

about:
  summary: Pulseq in Python
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/imr-framework/pypulseq
  documentation: https://pypulseq.readthedocs.io/
  repository: https://github.com/imr-framework/pypulseq

extra:
  recipe-maintainers:
    - schuenke
    - sravan953
    - wtclarke
